=== dmartinez82/LlenguatgesMarques23/xml/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="perfil" type="xs:anyURI"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="departamento" type="xs:string" />
                            <xs:element name="habilidades" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="habilidad" type="xs:string" minOccurs="0"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="imagenPerfil">
                                <xs:complexType>
                                    <xs:attribute name="location" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!-- DefiniciÃ³n del atributo id para el empleado -->
                        <xs:attribute name="id" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dmartinez82/LlenguatgesMarques23/xml/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo.xsl"?>
<empleados
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="esquema.xsd">
    <empleado id="1">
        <nombre perfil="http://linkedin.es/perfilfalso">Juan Pérez</nombre>
        <departamento>Recursos Humanos</departamento>
        <habilidades>
            <habilidad>Comunicación</habilidad>
            <habilidad>Negociación</habilidad>
        </habilidades>
        <imagenPerfil location="./img/perfil1.webp"/>
    </empleado>
    <empleado id="2">
        <nombre>María López</nombre>
        <departamento>Finanzas</departamento>
        <habilidades>
            <habilidad>Análisis financiero</habilidad>
        </habilidades>
        <imagenPerfil location="./img/perfil1.webp"/>
    </empleado>
    <empleado id="3">
        <nombre>Luisa Fernández</nombre>
        <departamento>Marketing</departamento>
        <habilidades>
            <habilidad>SEO</habilidad>
            <habilidad>Publicidad digital</habilidad>
            <habilidad>Redes sociales</habilidad>
        </habilidades>
        <imagenPerfil location="./img/perfil2.webp"/>
    </empleado>
    <empleado id="4">
        <nombre perfil="http://linkedin.es/perfilfalso2">Carlos Gómez</nombre>
        <departamento>Recursos Humanos</departamento>
        <habilidades />
        <imagenPerfil location="./img/perfil3.webp"/>
    </empleado>
    <empleado id="5">
        <nombre perfil="">Sandra Martínez</nombre>
        <departamento>TI</departamento>
        <imagenPerfil location=""/>
    </empleado>
</empleados>
